version: "3.8"

services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    container_name: "db-concord"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "local"
    volumes:
      - "./Src/Data/Migrations/:/docker-entrypoint-initdb.d"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge